#!/bin/sh
set -eu
TEST_ROOT=${TEST_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)}
DAS_ROOT=${DAS_ROOT:?set DAS_ROOT to the DAS source tree}
TMPDIR=${TMPDIR:?set TMPDIR to a writable temporary directory}
TMP=$TMPDIR/das-s6filter.$$
trap 'rm -f "$TMP".*' 0 1 2 3 15
printf 'main:\r\n\tmove 1,2 ; lower comment\r\n\thalt\r\n' > "$TMP.in"
"$DAS_ROOT/s6filter" - "$TMP.s6" < "$TMP.in"
printf 'MAIN:\n MOVE 1,2 ; LOWER COMMENT\n HALT\n' > "$TMP.canon"
"$DAS_ROOT/das" -S -O "$TMP.s6.dxr" "$TMP.s6"
"$DAS_ROOT/das" -A -O "$TMP.ascii.dxr" "$TMP.canon"
cmp "$TMP.s6.dxr" "$TMP.ascii.dxr"
printf '.SIXBIT /abc/\n' > "$TMP.bad"
if "$DAS_ROOT/s6filter" "$TMP.bad" "$TMP.bad.s6" >/dev/null 2>&1; then
    echo 's6filter accepted lowercase semantic data' >&2; exit 1
fi
printf 'MOVE 1,{FOO}\n' > "$TMP.bad"
if "$DAS_ROOT/s6filter" "$TMP.bad" "$TMP.bad.s6" >/dev/null 2>&1; then
    echo 's6filter accepted non-SIXBIT punctuation' >&2; exit 1
fi
"$DAS_ROOT/das" -A -F -O "$TMP.opt.dxr" "$TEST_ROOT/dxr-optimize.s"
"$TEST_ROOT/dxr-optimize-check.py" "$TMP.opt.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.win.dxr" "$TEST_ROOT/dxr-optimize-window.s"
"$TEST_ROOT/dxr-optimize-window-check.py" "$TMP.win.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.addiwin.dxr" "$TEST_ROOT/dxr-optimize-addi-window.s"
"$TEST_ROOT/dxr-optimize-addi-window-check.py" "$TMP.addiwin.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.addiov.dxr" "$TEST_ROOT/dxr-optimize-addi-overflow-v1.s"
"$TEST_ROOT/dxr-optimize-addi-overflow-v1-check.py" "$TMP.addiov.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.movefwd.dxr" "$TEST_ROOT/dxr-optimize-move-forward-v1.s"
"$TEST_ROOT/dxr-optimize-move-forward-v1-check.py" "$TMP.movefwd.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.moveifwd.dxr" "$TEST_ROOT/dxr-optimize-movei-forward-v1.s"
"$TEST_ROOT/dxr-optimize-movei-forward-v1-check.py" "$TMP.moveifwd.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.setmfwd.dxr" "$TEST_ROOT/dxr-optimize-setm-forward-v1.s"
"$TEST_ROOT/dxr-optimize-setm-forward-v1-check.py" "$TMP.setmfwd.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.zerocopy.dxr" "$TEST_ROOT/dxr-optimize-zero-copy-v1.s"
"$TEST_ROOT/dxr-optimize-zero-copy-v1-check.py" "$TMP.zerocopy.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.jrstnext.dxr" "$TEST_ROOT/dxr-optimize-jrst-next-v2.s"
"$DAS_ROOT/das" -A -O "$TMP.jrstnext.expected.dxr" "$TEST_ROOT/dxr-optimize-jrst-next-v2-expected.s"
cmp "$TMP.jrstnext.dxr" "$TMP.jrstnext.expected.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.lit.dxr" "$TEST_ROOT/dxr-optimize-literal.s"
"$TEST_ROOT/dxr-optimize-literal-check.py" "$TMP.lit.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.movei.dxr" "$TEST_ROOT/dxr-optimize-movei.s"
"$TEST_ROOT/dxr-optimize-movei-check.py" "$TMP.movei.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.half.dxr" "$TEST_ROOT/dxr-optimize-halfword.s"
"$TEST_ROOT/dxr-optimize-halfword-check.py" "$TMP.half.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.zero.dxr" "$TEST_ROOT/dxr-optimize-zero-pair.s"
"$TEST_ROOT/dxr-optimize-zero-pair-check.py" "$TMP.zero.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.skipbar.dxr" "$TEST_ROOT/dxr-optimize-skip-barrier-v1.s"
"$TEST_ROOT/dxr-optimize-skip-barrier-v1-check.py" "$TMP.skipbar.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.skipstate.dxr" "$TEST_ROOT/dxr-optimize-skip-state-v2.s"
"$TEST_ROOT/dxr-optimize-skip-state-v2-check.py" "$TMP.skipstate.dxr"
"$DAS_ROOT/das" -A -F -L "$TMP.labelxct.labels" -O "$TMP.labelxct.dxr" "$TEST_ROOT/dxr-optimize-label-xct-v1.s"
"$TEST_ROOT/dxr-optimize-label-xct-v1-check.py" "$TMP.labelxct.dxr" "$TMP.labelxct.labels"
"$DAS_ROOT/das" -A -F -L "$TMP.macrolabel.labels" -O "$TMP.macrolabel.dxr" "$TEST_ROOT/dxr-macro-opt-label-v1.s"
"$TEST_ROOT/dxr-macro-opt-label-v1-check.py" "$TMP.macrolabel.dxr" "$TMP.macrolabel.labels"
"$DAS_ROOT/das" -A -F -O "$TMP.eaaudit.dxr" "$TEST_ROOT/dxr-optimize-ea-audit-v1.s"
"$TEST_ROOT/dxr-optimize-ea-audit-v1-check.py" "$TMP.eaaudit.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.skipac0.dxr" "$TEST_ROOT/dxr-optimize-skip-ac0-v1.s"
"$TEST_ROOT/dxr-optimize-skip-ac0-v1-check.py" "$TMP.skipac0.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.zstore.dxr" "$TEST_ROOT/dxr-optimize-zero-store.s"
"$TEST_ROOT/dxr-optimize-zero-store-check.py" "$TMP.zstore.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.zstorefault.dxr" "$TEST_ROOT/dxr-optimize-zero-store-fault-v1.s"
"$TEST_ROOT/dxr-optimize-zero-store-fault-v1-check.py" "$TMP.zstorefault.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.moveihrrz.dxr" "$TEST_ROOT/dxr-optimize-movei-hrrz.s"
"$TEST_ROOT/dxr-optimize-movei-hrrz-check.py" "$TMP.moveihrrz.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.moveiunary.dxr" "$TEST_ROOT/dxr-optimize-movei-unary.s"
"$TEST_ROOT/dxr-optimize-movei-unary-check.py" "$TMP.moveiunary.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.immediate.dxr" "$TEST_ROOT/dxr-optimize-immediate.s"
"$TEST_ROOT/dxr-optimize-immediate-check.py" "$TMP.immediate.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.subiflags.dxr" "$TEST_ROOT/dxr-optimize-subi-flags-v1.s"
"$TEST_ROOT/dxr-optimize-subi-flags-v1-check.py" "$TMP.subiflags.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.shift.dxr" "$TEST_ROOT/dxr-optimize-shift.s"
"$TEST_ROOT/dxr-optimize-shift-check.py" "$TMP.shift.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.lshrmask.dxr" "$TEST_ROOT/dxr-optimize-lshr-mask-v1.s"
"$TEST_ROOT/dxr-optimize-lshr-mask-v1-check.py" "$TMP.lshrmask.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.testnonskip.dxr" "$TEST_ROOT/dxr-optimize-test-nonskip.s"
"$TEST_ROOT/dxr-optimize-test-nonskip-check.py" "$TMP.testnonskip.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.storefwd.dxr" "$TEST_ROOT/dxr-optimize-store-forward.s"
"$TEST_ROOT/dxr-optimize-store-forward-check.py" "$TMP.storefwd.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.loadstore.dxr" "$TEST_ROOT/dxr-optimize-load-store.s"
"$TEST_ROOT/dxr-optimize-load-store-check.py" "$TMP.loadstore.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.accesskind.dxr" "$TEST_ROOT/dxr-optimize-access-kind-v1.s"
"$TEST_ROOT/dxr-optimize-access-kind-v1-check.py" "$TMP.accesskind.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.skipfold.dxr" "$TEST_ROOT/dxr-optimize-skip-fold.s"
"$TEST_ROOT/dxr-optimize-skip-fold-check.py" "$TMP.skipfold.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.unaryfold.dxr" "$TEST_ROOT/dxr-optimize-unary-fold.s"
"$TEST_ROOT/dxr-optimize-unary-fold-check.py" "$TMP.unaryfold.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.movnov.dxr" "$TEST_ROOT/dxr-optimize-movn-overflow-v1.s"
"$TEST_ROOT/dxr-optimize-movn-overflow-v1-check.py" "$TMP.movnov.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.overwrite.dxr" "$TEST_ROOT/dxr-optimize-overwrite.s"
"$TEST_ROOT/dxr-optimize-overwrite-check.py" "$TMP.overwrite.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.faultorder.dxr" "$TEST_ROOT/dxr-optimize-fault-order-v1.s"
"$TEST_ROOT/dxr-optimize-fault-order-v1-check.py" "$TMP.faultorder.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.pushlive.dxr" "$TEST_ROOT/dxr-optimize-push-live.s"
"$DAS_ROOT/das" -A -O "$TMP.pushlive.expected.dxr" "$TEST_ROOT/dxr-optimize-push-live-expected.s"
cmp "$TMP.pushlive.dxr" "$TMP.pushlive.expected.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.pushfault.dxr" "$TEST_ROOT/dxr-optimize-push-fault-v1.s"
"$TEST_ROOT/dxr-optimize-push-fault-v1-check.py" "$TMP.pushfault.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.caizero.dxr" "$TEST_ROOT/dxr-optimize-cai-zero.s"
"$TEST_ROOT/dxr-optimize-cai-zero-check.py" "$TMP.caizero.dxr"
"$DAS_ROOT/das" -A -F -O "$TMP.caiflags.dxr" "$TEST_ROOT/dxr-optimize-cai-flags-v1.s"
"$TEST_ROOT/dxr-optimize-cai-flags-v1-check.py" "$TMP.caiflags.dxr"
echo 'DAS delayed MOVE/PUSH liveness contract passed'
echo 'DAIMOS SIXBIT filter contract passed'
